swagger: "2.0"
info:
  version: '1.0'
  title: challenge-api-service-prod
host: "ss6b2ke2ca.execute-api.us-east-1.amazonaws.com"
basePath: /Prod
schemes:
  - https
definitions:
  RateQuoteQuery:
    properties:
      loanSize:
        type: number
        description: Loan size in dollars
      creditScore:
        type: integer
        minimum: 300
        maximum: 800
        description: The borrowers credit score
      propertyType:
        type: string
        enum:
          - SingleFamily
          - Condo
          - Townhouse
          - MultiFamily
        description: The type of property for which a mortgage is being requested
      occupancy:
        type: string
        enum:
          - Primary
          - Secondary
          - Investment
        description: How the borrower will use the property
    required:
      - loanSize
      - creditScore
      - propertyType
      - occupancy
    example:
      loanSize: 400000
      creditScore: 720
      propertyType: Condo
      occupancy: Primary
  RateQuotes:
    properties:
      done:
        type: boolean
        description: A flag indicating if all lenders have provided rates
      rateQuotes:
        type: array
        items:
          type: object
          properties:
            lenderName:
              type: string
              example: TFB Federal Credit Union
              description: The name of the lender
            loanType:
              type: string
              example: 30YR Fixed
              description: The type of loan
            interestRate:
              type: number
              example: 4.125
              description: The interest rate of the loan
            closingCosts:
              type: number
              example: 10000
              description: The fees the lender with charge when the loan is closed
            monthlyPayment:
              type: number
              example: 1000
              description: the required monthly payment
            apr:
              type: number
              example: 4.25
              description: the APR of the loan
          required:
            - lenderName
            - loanType
            - interestRate
            - closingCosts
            - monthlyPayment
            - apr
    required:
      - done
      - rateQuotes
  Error:
    properties:
      errors:
        type: array
        items:
          type: string
        description: A list of errors
    required:
      - errors
securityDefinitions:
  RGAuth:
    type: apiKey
    in: header
    name: Authorization
security:
  - RGAuth: []
paths:
  "/ratequotes":
    post:
      summary: Create a request for rate quotes
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: query
          schema:
            $ref: '#/definitions/RateQuoteQuery'
      responses:
        '200':
          description: 'Success'
          schema:
            type: object
            properties:
              requestId:
                type: string
            required:
            - requestId
        '404':
          description: 'Not Found'
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: 'Not Authorized'
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: 'Invalid Request'
          schema:
            $ref: '#/definitions/Error'
    get:
      summary: check the status of a rate quote request and get the results
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: "query"
          name: requestId
          required: true
          type: string
      responses:
        '200':
          description: 'Success'
          schema:
            $ref: '#/definitions/RateQuotes'
        '404':
          description: 'Not Found'
          schema:
            $ref: '#/definitions/Error'
        '401':
          description: 'Not Authorized'
          schema:
            $ref: '#/definitions/Error'
        '400':
          description: 'Invalid Request'
          schema:
            $ref: '#/definitions/Error'